/**
 * Official printable park plaque — matches the outdoor tree sign design.
 * Admin-only: QR is generated by the live API and points to /t/{accessToken}.
 */
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { fetchQrCode, fetchTreeBySlug } from '../api/client';
import LoadingSpinner from '../components/LoadingSpinner';
import { useAuth } from '../context/AuthContext';
import { useLanguage } from '../context/LanguageContext';
import { t } from '../i18n/ui';

const PLAQUE_COPY = {
  'syzygium-guineense': {
    localName: 'UMUGOTE',
    englishName: 'Waterberry / Water Pear',
    family: 'Myrtaceae',
    akamaro:
      'Igiti cyacyo kirakomeye kandi gishobora gukoreshwa mu gukora no kubaka ibintu bitandukanye. Imbuto zacyo ziribwa n\'abantu ndetse n\'inyamaswa zitandukanye, cyane cyane inyoni n\'inguge.',
    ubuvuzi:
      "Imbuto z'umugote zikoreshwa mu buvuzi gakondo mu kuvura amacinya. Ibishishwa by'igiti bitekwa, maze amazi yabyo agakoreshwa mu kuvura gucibwamo.",
    uses: [
      'Firewood and strong wood for making and building various items.',
      'The fruits are eaten by humans, birds and monkeys.',
      'The fruits are used as a traditional remedy for dysentery.',
      'A decoction of the bark is used as an antidiarrheic.',
    ],
  },
  'ficus-ovata': {
    localName: 'UMUREHE',
    englishName: 'oval-leaved fig',
    family: 'Moraceae',
    akamaro: 'Igiti cy\'igicucu Inkingi z\'ubwubatsi Imyenda y\'igiti (barkcloth)',
    ubuvuzi:
      'Igishihwa n\'ibyatsi bikoreshwa ku ndwara zo mu nda n\'amacinya. Amateke y\'igiti yakoreshejwe ku ndwara z\'uruhu nka ringworm.',
    uses: [
      'Planted for shade, live fences, and boundary marking.',
      'Bark fibre used for traditional barkcloth and garments.',
      'Stem-bark decoction used for gastrointestinal infections and diarrhoea.',
      'Latex traditionally applied for skin conditions such as ringworm.',
    ],
  },
  'aeschynomene-elaphroxylon': {
    localName: 'UMUBURU',
    englishName: 'ambatch / pith-tree',
    family: 'Fabaceae',
    akamaro: 'Ibiti byoroshye byo gukora floats n\'amato Ubucukuzi bw\'ubusitani',
    ubuvuzi:
      'Ntibikoreshwa cyane nk\'ubuvuzi — ahubwo ni igiti cy\'amazi gifite agaciro ku bucukuzi n\'ubuzima bw\'ibishanga.',
    uses: [
      'Lightweight rot-resistant wood for fishing-net floats.',
      'Trunks lashed together to make rafts and small boats.',
      'Local crafts such as stools and sun screens.',
      'Sometimes planted as an ornamental wetland shrub.',
    ],
  },
  'albizia-versicolor': {
    localName: 'UMUBUBA',
    englishName: 'poison-pod albizia / large-leaved albizia',
    family: 'Fabaceae',
    akamaro:
      'Kivangwa n\'imyaka. Bakibazamo ibikoresho byo mu gikoni. Igiti cy\'igicucu n\'ubuhinzi bw\'ibiti.',
    ubuvuzi:
      'Igishihwa n\'imizi bikoreshwa mu buvuzi gakondo: kuvura inzoka zo munda, kwongera amaraso, kubyimbirwa, indwara z\'ibanga, kubabara umutwe, impfu n\'uburwayi bwo mu zuru.',
    uses: [
      'Medicinal bark and roots for anaemia, swollen glands, anthelmintic and headache relief.',
      'Powdered bark sniffed for coughs, headache and sinusitis.',
      'Timber for building; bark fibre for household items.',
      'Firewood and agroforestry shade tree — note toxic pods for livestock.',
    ],
  },
  'bambusa-vulgaris': {
    localName: 'UMUGANO',
    englishName: 'common bamboo',
    family: 'Poaceae',
    akamaro:
      'Umulimbo, kubaka, gukora uruzitiro, kuboha ibikoresho byo mu rugo. Amababi bayagaburira amatungo. Barwanya isuri ku nkengero z\'imigezi. Uyu mugano ni gakondo mu Rwanda.',
    ubuvuzi:
      'Amababi barayavuza. Hakorwamo ibikoresho by\'ubukorikori (inkooko, inkangara, intaro, n\'ibindi).',
    uses: [
      'Ornamental plant, fence, construction and basketry.',
      'Used to make boats, furniture and paper.',
      'Split stems for brooms, baskets and musical instruments.',
      'Leaves as livestock fodder; planted to control riverbank erosion.',
    ],
  },
  'erythrina-abyssinica': {
    localName: 'UMUKO',
    englishName: 'red hot poker tree / Abyssinian coral tree',
    family: 'Fabaceae',
    akamaro:
      'Kubandwa Ryangombe. Gufumbira ubutaka — gukoresha nk\'ifumbire y\'ubutaka.',
    ubuvuzi:
      'Indwara z\'umwijima — igishihwa cy\'igiti gikoreshwa mu kuvura indwara z\'umwijima. Inzoka zo munda, ibinyoro, ibisebe, umwijima na malariya. Indeberezi mu burobyi — ubusa bw\'igishihwa.',
    uses: [
      'Socio-cultural: used in religious ceremonies of Ryangombe.',
      'Traditional medicine: stem bark for liver complaints.',
      'Fishing: corky bark used as floats.',
      'Agroforestry: shade and soil enrichment (green manure).',
    ],
  },
  'olea-europaea-subsp-africana': {
    localName: 'UMUNZENZE',
    englishName: 'wild olive / African olive',
    family: 'Oleaceae',
    akamaro:
      'Amababi atekwamo icyayi. Igiti kibazwamo amashusho, imidaho n\'ibindi bikoresho byo mu rugo.',
    ubuvuzi:
      'Umuti ukozwe mu mababi n\'imbuto uvura amaso, ukagabanya umuvuduko w\'amaraso, ugatuma impyiko zikora neza, ukavura no mu mihogo. Amababi afite kurinda kanseri, kubyimbirwa, diabete n\'umuvuduko w\'amaraso.',
    uses: [
      'Leaf tea from Umunzenze leaves.',
      'Hard wood carved into figures, spoons and household items.',
      'Traditional medicine: eye infection, sore throat, headache, hypertension.',
      'Parts used: leaves, bark, roots, flowers and seeds.',
    ],
  },
  'senegalia-polyacantha-campylacantha': {
    localName: 'UMUHARATA',
    englishName: "falcon's claw acacia / white thorn",
    family: 'Fabaceae',
    akamaro:
      'Gushyira nitrogen mu butaka. Imizi yirukana inzoka n\'imbeba.',
    ubuvuzi:
      'Kugombora urumwe n\'inzoka — imizi ikoreshwa mu kuvura inzoka. Amababi akafashwa, akumurwa, akavunika akashyirwa ku bisebe.',
    uses: [
      'Pioneer of woodland forest; nitrogen fixation.',
      'Traditional medicine: leaves pounded, dried and applied to sores.',
      'Roots used to treat snakebites.',
      'Roots recorded as repelling snakes, crocodiles and rats.',
    ],
  },
  'entada-abyssinica': {
    localName: 'UMUSANGE',
    englishName: 'splinter bean',
    family: 'Fabaceae (Mimosaceae)',
    akamaro: 'Umusange — igiti kinini cy\'umuryango wa Fabaceae.',
    ubuvuzi:
      'Abavuzi gakonda bayivuza: Inkorora, Rubagimpande, indwara z\'ubuhumekero, Gucibwamo, umuriro, gukuuramo inda. Ubushakashatsi: entadanin ivura kanseri, ikagira imbaraga zo kurwanya bakteriya.',
    uses: [
      'Traditional medicine for cough, respiratory disease, diarrhoea and fever.',
      'Research: entadanin with antibacterial activity against Salmonella typhimurium.',
      'Documented antioxidant and anticancer activity in scientific studies.',
    ],
  },
  'phragmites-mauritianus': {
    localName: 'IMISEKE',
    englishName: 'reed grass / African reed',
    family: 'Poaceae',
    akamaro:
      'Gukora plafond y\'imiseke. Gukora urugo rw\'imiseke. Imiseke irinda inkombe z\'imigezi cyangwa ibiyaga.',
    ubuvuzi:
      'Abaturage bo ku nkengero z\'ikiyaga cya Ruhondo bakoramo Urusengo — igikinisho cy\'umuziki.',
    uses: [
      'Stabilise river banks and lake shores.',
      'Ceilings (plafond) and reed fences for houses.',
      'Musical instrument Urusengo from leaves (Lake Ruhondo area).',
    ],
  },
  'maesa-lanceolata': {
    localName: 'UMUHANGA',
    englishName: 'false assegai',
    family: 'Myrsinaceae',
    akamaro: 'Imihango yo Kubandwa. Kuvura ibisazi.',
    ubuvuzi:
      'Umuhanga — igiti cy\'umuryango wa Myrsinaceae. Imbuto zafite anticancer n\'antifungal activity.',
    uses: [
      'Culturally used in the Kubandwa ceremony.',
      'Traditional treatment of mental illness (ibisazi).',
      'Seeds have anticancer compounds and antifungal activity.',
    ],
  },
  'senegalia-polyacantha-ruganambuga': {
    localName: 'RUGANAMBUGA',
    englishName: "falcon's claw acacia",
    family: 'Fabaceae',
    akamaro:
      'Kugombora urumwe n\'inzoka. Gushyira nitrogen mu butaka. Imizi yirukana inzoka n\'imbeba.',
    ubuvuzi:
      'Amababi akafashwa ku bisebe; imizi ikoreshwa mu kuvura inzoka. Amazina: Umuharata · Ruganambuga.',
    uses: [
      'Pioneer of woodland forest; nitrogen fixation.',
      'Leaves pounded and applied to sores; roots for snakebites.',
      'Roots emit compounds that repel snakes, crocodiles and rats.',
    ],
  },
  'elaeis-guineensis': {
    localName: 'IKIGAZI',
    englishName: 'African oil palm',
    family: 'Arecaceae',
    akamaro:
      'Amavuta y\'amamesa akoreshwa mu guteka ibiryo, cosmetics no mu gukora amasabune. Mu mababi bakoramo inkangara n\'imikubuzo.',
    ubuvuzi:
      'Ikigazi gishobora kugeza mu burebure bwa metero 20. Agakoko Elaeidobius kamerunicus gituma kizana imbuto.',
    uses: [
      'Palm oil for cooking, cosmetics and soap; kernel oil from the seed.',
      'Leaves and fibres for thatch, baskets, brooms and ropes.',
      'Pollinated by Elaeidobius kamerunicus.',
    ],
  },
  'chrysophyllum-gorungosanum': {
    localName: 'UMUTOYI',
    englishName: 'fluted milkwood',
    family: 'Sapotaceae',
    akamaro:
      'Latex, ibiti byo kubaka no kubaza, inkwi n\'amakara; indabo zifasha inzuki.',
    ubuvuzi:
      'Umutoyi ni igiti kinini cy\'ishyamba gihora kibisi, gifite uruti rukunze kuba rufite ubusate kandi gisohora latex.',
    uses: [
      'Latex, timber and local construction wood.',
      'Firewood and charcoal.',
      'Bee forage and canopy habitat in evergreen forest.',
    ],
  },
  'phoenix-reclinata': {
    localName: 'UMUKINDO',
    englishName: 'wild date palm / Senegal date palm',
    family: 'Arecaceae',
    akamaro:
      'Imbuto ziraribwa. Amababi akiri mato bayakoramo imikeka, imikubuzo. Ku munsi wa mashami (Kiriziya Gatorika) bakoresha amababi y\'umukindo akiri mato.',
    ubuvuzi:
      'Umukindo ni igisabo cy\'umuryango wa Arecaceae. Umuti wo mu mababi ushobora gukoreshwa mu gukora inzoga y\'igisabo.',
    uses: [
      'The fruit are edible.',
      'Sap gives palm wine.',
      'Fibre of young unopened leaves used for carpets, kilts and brooms.',
      'Young palm leaves used on Palm Sunday in the Catholic Church.',
    ],
  },
  'millettia-laurentii': {
    localName: 'UMUYOGORO',
    englishName: 'faux ebony / African rosewood / wenge',
    family: 'Fabaceae',
    akamaro:
      'Imbaho nziza (Wenge). Igiti cy\'umulimbo.',
    ubuvuzi:
      'Bark ikivura indwara z\'umwijima, diabete, umuriro, indwara z\'uruhu n\'ibindi. Bark ifite imikorere yo kurwanya udukoko.',
    uses: [
      'Dark timber marketed as wenge, African rosewood or faux ebony.',
      'Endangered on the IUCN Red List.',
      'Bark decoction for liver complaints in traditional medicine.',
      'Bark has insecticidal properties; ornamental shade tree.',
    ],
  },
  'ficus-thonningii': {
    localName: 'UMUVUMU',
    englishName: 'wild fig',
    family: 'Moraceae',
    akamaro:
      'Igishishwa cy\'igiti bagikoragamo inkanda. Babazagamo imivure, amasekuru n\'intebe. Amababi agaburira amatungo mu gihe cy\'impeshi.',
    ubuvuzi:
      'Icyo bavuza: amababi, imizi. Indwara zivugwa: gucibwamo, mburugu, diabete, ibihushi, ibisebe, bronchiite, imuyoboro w\'inkari.',
    uses: [
      'Planted around rural houses and royal burial grounds.',
      'Bole used for boats, mortars and troughs; bark for inkanda cloth.',
      'Leaves used as livestock fodder in dry seasons.',
      'Leaves and figs used in traditional medicine for diarrhoea, gonorrhoea and diabetes.',
    ],
  },
  'trema-orientalis': {
    localName: 'UMUDOBORI',
    englishName: 'pigeon wood / gunpowder tree',
    family: 'Cannabaceae',
    akamaro: 'Inkwi zo gucana.',
    ubuvuzi:
      'Amababi n\'igishishwa cy\'igiti bivura inkorora, kubabara mu mihogo, asima n\'indwara z\'ubuhumekero.',
    uses: [
      'Firewood for cooking and heating.',
      'Leaves and bark used in traditional medicine for coughs and sore throat.',
      'Traditional use for asthma and bronchitis.',
    ],
  },
  'newtonia-buchananii': {
    localName: 'UMUKEREKO',
    englishName: 'forest newtonia / African newtonia',
    family: 'Fabaceae',
    akamaro:
      'Imbaho. Kivangwa n\'imyaka. Kugaburira amatungo. Inzuki zirahova.',
    ubuvuzi:
      'Umukereko ni igiti kinini cy\'ishyamba. Amababi n\'imbuto bigaburira amatungo; amashurwe afasha inzuki.',
    uses: [
      'Timber for construction and carpentry.',
      'Agroforestry: grown with crops; leaves and pods as livestock fodder.',
      'Flowers provide nectar and pollen for bees.',
    ],
  },
  'blighia-unijugata': {
    localName: 'UMUTURAMUGINA',
    englishName: 'triangle-top',
    family: 'Sapindaceae',
    akamaro: 'Imbaho zo kubaka ibyoroshye.',
    ubuvuzi:
      'Mu buvuzi gakondo bakivuza rubagimpande, ububabare bw\'impyiko, no kumugara kw\'ingingo. Amababi, igishishwa n\'imizi bikoreshwa mu kabyaza abagore.',
    uses: [
      'Traditional medicine for rheumatism, kidney pain and joint stiffness.',
      'Leaves, bark and roots recorded as oxytocic in childbirth.',
      'Wood used in light construction.',
    ],
  },
  'croton-megalocarpus': {
    localName: 'UMUNEGE',
    englishName: 'croton tree / croto tree',
    family: 'Euphorbiaceae',
    akamaro:
      'Urugara ku bantu n\'inyamaswa. Kurinda umuyaga. Gufata ubutaka. Amavuta y\'imbuto muri moteri.',
    ubuvuzi:
      'Umunege ni igiti kiba mu mashyamba yo mu misozi miremire nka Nyungwe na Gishwati. Imbuto zivamo amavuta akoreshwa muri za moteri; ntahumanya ikirere.',
    uses: [
      'Shade for people and wildlife; wind protection and soil conservation.',
      'Nuts yield oil used in engines as biofuel or biodiesel.',
      'Highland forest tree of Rwanda (Nyungwe, Gishwati and similar areas).',
    ],
  },
  'entada-abyssinica-022': {
    localName: 'UMUSANGE',
    englishName: 'splinter bean',
    family: 'Fabaceae (Mimosaceae)',
    akamaro:
      'Abavuzi gakonda bayivuza: Inkorora, Rubagimpande, indwara z\'ubuhumekero, Gucibwamo, umuriro, gukuuramo inda.',
    ubuvuzi:
      'Ubushakashatsi bwabonye muri icyo giti entadanin ivura kanseri, ikarwanya bakteriya ndetse na Salmonella typhimurium itera guhitwa no kubabara mu nda.',
    uses: [
      'Traditional medicine for cough, side pain, respiratory disease, diarrhoea and fever.',
      'Research: entadanin with antibacterial activity against Salmonella typhimurium.',
      'Documented antioxidant and anticancer activity in scientific studies.',
    ],
  },
};

function ParkLogo() {
  return (
    <img
      className="park-plaque-logo"
      src="/kigali-eco-park-logo.png"
      alt="Kigali Eco-Park"
    />
  );
}

export default function QrLabelPage() {
  return <QrLabelPageContent />;
}

function QrLabelPageContent() {
  const { slug } = useParams();
  const { language } = useLanguage();
  const { user } = useAuth();
  const [qr, setQr] = useState(null);
  const [treeEn, setTreeEn] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    setError('');
    setQr(null);
    Promise.all([
      fetchQrCode(slug, user?.token),
      fetchTreeBySlug(slug, 'en').catch(() => null),
    ])
      .then(([qrData, en]) => {
        setQr(qrData);
        setTreeEn(en);
      })
      .catch((err) => setError(err.message));
  }, [slug, user?.token]);

  if (!qr && !error) {
    return <LoadingSpinner label={t(language, 'loadingQr')} />;
  }

  if (error) {
    return (
      <div className="section-container py-20 text-center">
        <p className="text-gray-600">{t(language, 'qrLoadError')}</p>
        <Link to="/admin/qr" className="btn btn-primary mt-4">{t(language, 'adminQrCodes')}</Link>
      </div>
    );
  }

  const plaque = PLAQUE_COPY[slug] || {};
  const localName = (plaque.localName || treeEn?.commonName || slug).toUpperCase();
  const englishName = plaque.englishName || treeEn?.commonName || '';
  const family = plaque.family || treeEn?.family || '';
  const uses = plaque.uses || [];
  const akamaro = plaque.akamaro || '';
  const ubuvuzi = plaque.ubuvuzi || '';

  return (
    <div className="qr-label-page bg-surface px-4 py-8 sm:px-6">
      {/* Print/PDF = green A4 plaque only, not the full website page */}
      <style>{`
        @media print {
          @page {
            size: A4 portrait;
            margin: 0;
          }
        }
      `}</style>

      <div className="no-print mx-auto mb-6 flex max-w-xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <Link to="/admin/qr" className="text-sm font-medium text-primary-dark hover:underline">
            ← {t(language, 'adminQrCodes')}
          </Link>
          <p className="mt-2 text-sm text-gray-600">{t(language, 'downloadPaperHint')}</p>
          <div className="mt-3 flex flex-wrap gap-2">
            {Object.keys(PLAQUE_COPY).map((treeSlug) => (
              <Link
                key={treeSlug}
                to={`/admin/qr-label/${treeSlug}`}
                className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${
                  treeSlug === slug
                    ? 'bg-primary text-white'
                    : 'bg-white text-primary-dark ring-1 ring-primary/20 hover:bg-primary/5'
                }`}
              >
                {PLAQUE_COPY[treeSlug].localName}
              </Link>
            ))}
          </div>
        </div>
        <div className="flex flex-wrap gap-3">
          <a href={qr.url} className="btn btn-secondary !rounded-xl !px-4 !py-2 text-xs">
            {t(language, 'fullGuideAfterScan')}
          </a>
          <button
            type="button"
            className="btn btn-primary !rounded-xl !px-5 !py-2.5 text-sm"
            onClick={() => {
              const previousTitle = document.title;
              document.title = ' ';
              window.print();
              setTimeout(() => {
                document.title = previousTitle;
              }, 500);
            }}
          >
            {t(language, 'downloadFullPaper')}
          </button>
        </div>
      </div>

      <div className="tree-label-sheet mx-auto">
        <section className="park-plaque" aria-label={t(language, 'printableTreeLabel')}>
          <div className="park-plaque-border">
            <div className="park-plaque-content">
              <div className="park-plaque-header">
                <div className="park-plaque-header-text">
                  <h1 className="park-plaque-scientific">
                    <em>{qr.scientificName}</em>
                  </h1>
                  <p className="park-plaque-line park-plaque-line-header">
                    <strong>Local name:</strong> {localName}
                  </p>
                  {family && (
                    <p className="park-plaque-line park-plaque-line-header">
                      <strong>Family:</strong> {family}
                    </p>
                  )}
                </div>
                <div className="park-plaque-qr-box">
                  <img
                    src={qr.qrCodeBase64}
                    alt={`Scan for ${qr.scientificName} details`}
                    className="park-plaque-qr"
                  />
                </div>
              </div>

              <div className="park-plaque-body">
                <div className="park-plaque-col">
                  {akamaro && (
                    <p className="park-plaque-line park-plaque-gap">
                      <strong className="park-plaque-line-label">Akamaro:</strong> {akamaro}
                    </p>
                  )}
                  {ubuvuzi && (
                    <p className="park-plaque-line">
                      <strong className="park-plaque-line-label">Ubuvuzi:</strong> {ubuvuzi}
                    </p>
                  )}
                </div>

                <div className="park-plaque-col">
                  <p className="park-plaque-line">
                    <strong className="park-plaque-line-label">Common name:</strong> {englishName}
                  </p>
                  {uses.length > 0 && (
                    <div className="park-plaque-uses">
                      <p className="park-plaque-line">
                        <strong className="park-plaque-line-label">Uses:</strong>
                      </p>
                      {uses.map((item) => (
                        <p key={item} className="park-plaque-line">
                          {item}
                        </p>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              <div className="park-plaque-brand">
                <ParkLogo />
              </div>
            </div>
          </div>
        </section>
        <p className="no-print mt-3 text-center text-xs text-gray-500">
          A4 portrait (210 × 297 mm) — print or save as PDF with background graphics enabled
        </p>
      </div>

      <div className="no-print mx-auto mt-8 max-w-xl rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-950">
        <strong>{t(language, 'importantBeforePrinting')}</strong>
        <p className="mt-2">{t(language, 'productionQrWarning')}</p>
        <p className="mt-3 font-medium">This label’s QR opens the tree page:</p>
        <code className="mt-1 block break-all rounded-lg bg-white px-3 py-2 text-xs text-primary-dark">{qr.url}</code>
        <p className="mt-2 text-xs text-amber-900/80">Tree ID: {qr.treeId}</p>
      </div>
    </div>
  );
}
