import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { fetchQrCode, fetchTreeBySlug } from '../api/client';
import LoadingSpinner from '../components/LoadingSpinner';
import { useLanguage } from '../context/LanguageContext';
import { t } from '../i18n/ui';

/**
 * Official printable park plaque — matches the outdoor tree sign design.
 * QR is generated by the live API and always points to /scan/{treeId}.
 */
const PLAQUE_COPY = {
  'syzygium-guineense': {
    localName: 'UMUGOTE',
    englishName: 'Waterberry / Water Pear',
    family: 'Myrtaceae',
    akamaro:
      'Igiti cyacyo kirakomeye kandi gishobora gukoreshwa mu gukora no kubaka ibintu bitandukanye. Imbuto zacyo ziribwa n\'abantu ndetse n\'inyamaswa zitandukanye, cyane cyane inyoni n\'inguge.',
    ubuvuzi:
      "Imbuto z'umugote zikoreshwa mu buvuzi gakondo mu kuvura amacinya. Ibishishwa by'igiti bitekwa, maze amazi yabyo agakoreshwa mu kuvura gucibwamo.",
    uses: [
      'Firewood and strong wood for making and building various items.',
      'The fruits are eaten by humans, birds and monkeys.',
      'The fruits are used as a traditional remedy for dysentery.',
      'A decoction of the bark is used as an antidiarrheic.',
    ],
  },
  'ficus-ovata': {
    localName: 'UMUREHE',
    englishName: 'oval-leaved fig',
    family: 'Moraceae',
    akamaro: 'Igiti cy\'igicucu Inkingi z\'ubwubatsi Imyenda y\'igiti (barkcloth)',
    ubuvuzi:
      'Igishihwa n\'ibyatsi bikoreshwa ku ndwara zo mu nda n\'amacinya. Amateke y\'igiti yakoreshejwe ku ndwara z\'uruhu nka ringworm.',
    uses: [
      'Planted for shade, live fences, and boundary marking.',
      'Bark fibre used for traditional barkcloth and garments.',
      'Stem-bark decoction used for gastrointestinal infections and diarrhoea.',
      'Latex traditionally applied for skin conditions such as ringworm.',
    ],
  },
  'aeschynomene-elaphroxylon': {
    localName: 'UMUBURU',
    englishName: 'ambatch / pith-tree',
    family: 'Fabaceae',
    akamaro: 'Ibiti byoroshye byo gukora floats n\'amato Ubucukuzi bw\'ubusitani',
    ubuvuzi:
      'Ntibikoreshwa cyane nk\'ubuvuzi — ahubwo ni igiti cy\'amazi gifite agaciro ku bucukuzi n\'ubuzima bw\'ibishanga.',
    uses: [
      'Lightweight rot-resistant wood for fishing-net floats.',
      'Trunks lashed together to make rafts and small boats.',
      'Local crafts such as stools and sun screens.',
      'Sometimes planted as an ornamental wetland shrub.',
    ],
  },
};

function ParkLogo() {
  return (
    <img
      className="park-plaque-logo"
      src="/kigali-eco-park-logo.png"
      alt="Kigali Eco-Park"
    />
  );
}

export default function QrLabelPage() {
  const { slug } = useParams();
  const { language } = useLanguage();
  const [qr, setQr] = useState(null);
  const [treeEn, setTreeEn] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    setError('');
    Promise.all([
      fetchQrCode(slug),
      fetchTreeBySlug(slug, 'en').catch(() => null),
    ])
      .then(([qrData, en]) => {
        setQr(qrData);
        setTreeEn(en);
      })
      .catch((err) => setError(err.message));
  }, [slug]);

  if (!qr && !error) {
    return <LoadingSpinner label={t(language, 'loadingQr')} />;
  }

  if (error) {
    return (
      <div className="section-container py-20 text-center">
        <p className="text-gray-600">{t(language, 'qrLoadError')}</p>
        <Link to="/trees" className="btn btn-primary mt-4">{t(language, 'backToList')}</Link>
      </div>
    );
  }

  const plaque = PLAQUE_COPY[slug] || {};
  const localName = (plaque.localName || treeEn?.commonName || slug).toUpperCase();
  const englishName = plaque.englishName || treeEn?.commonName || '';
  const family = plaque.family || treeEn?.family || '';
  const uses = plaque.uses || [];
  const akamaro = plaque.akamaro || '';
  const ubuvuzi = plaque.ubuvuzi || '';

  return (
    <div className="qr-label-page bg-surface px-4 py-8 sm:px-6">
      {/* Print/PDF = green A4 plaque only, not the full website page */}
      <style>{`
        @media print {
          @page {
            size: A4 portrait;
            margin: 0;
          }
        }
      `}</style>

      <div className="no-print mx-auto mb-6 flex max-w-xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <Link to="/trees" className="text-sm font-medium text-primary-dark hover:underline">
            ← {t(language, 'backToList')}
          </Link>
          <p className="mt-2 text-sm text-gray-600">{t(language, 'downloadPaperHint')}</p>
          <div className="mt-3 flex flex-wrap gap-2">
            {Object.keys(PLAQUE_COPY).map((treeSlug) => (
              <Link
                key={treeSlug}
                to={`/qr-label/${treeSlug}`}
                className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${
                  treeSlug === slug
                    ? 'bg-primary text-white'
                    : 'bg-white text-primary-dark ring-1 ring-primary/20 hover:bg-primary/5'
                }`}
              >
                {PLAQUE_COPY[treeSlug].localName}
              </Link>
            ))}
          </div>
        </div>
        <div className="flex flex-wrap gap-3">
          <Link to={`/scan/${qr.treeId}`} className="btn btn-secondary !rounded-xl !px-4 !py-2 text-xs">
            {t(language, 'fullGuideAfterScan')}
          </Link>
          <button
            type="button"
            className="btn btn-primary !rounded-xl !px-5 !py-2.5 text-sm"
            onClick={() => {
              const previousTitle = document.title;
              document.title = ' ';
              window.print();
              setTimeout(() => {
                document.title = previousTitle;
              }, 500);
            }}
          >
            {t(language, 'downloadFullPaper')}
          </button>
        </div>
      </div>

      <div className="tree-label-sheet mx-auto">
        <section className="park-plaque" aria-label={t(language, 'printableTreeLabel')}>
          <div className="park-plaque-border">
            <div className="park-plaque-content">
              <div className="park-plaque-header">
                <div className="park-plaque-header-text">
                  <h1 className="park-plaque-scientific">
                    <em>{qr.scientificName}</em>
                  </h1>
                  <p className="park-plaque-line park-plaque-line-header">
                    <strong>Local name:</strong> {localName}
                  </p>
                  {family && (
                    <p className="park-plaque-line park-plaque-line-header">
                      <strong>Family:</strong> {family}
                    </p>
                  )}
                </div>
                <div className="park-plaque-qr-box">
                  <img
                    src={qr.qrCodeBase64}
                    alt={`Scan for ${qr.scientificName} details`}
                    className="park-plaque-qr"
                  />
                </div>
              </div>

              <div className="park-plaque-body">
                <div className="park-plaque-col">
                  {akamaro && (
                    <p className="park-plaque-line park-plaque-gap">
                      <strong className="park-plaque-line-label">Akamaro:</strong> {akamaro}
                    </p>
                  )}
                  {ubuvuzi && (
                    <p className="park-plaque-line">
                      <strong className="park-plaque-line-label">Ubuvuzi:</strong> {ubuvuzi}
                    </p>
                  )}
                </div>

                <div className="park-plaque-col">
                  <p className="park-plaque-line">
                    <strong className="park-plaque-line-label">Common name:</strong> {englishName}
                  </p>
                  {uses.length > 0 && (
                    <div className="park-plaque-uses">
                      <p className="park-plaque-line">
                        <strong className="park-plaque-line-label">Uses:</strong>
                      </p>
                      {uses.map((item) => (
                        <p key={item} className="park-plaque-line">
                          {item}
                        </p>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              <div className="park-plaque-brand">
                <ParkLogo />
              </div>
            </div>
          </div>
        </section>
        <p className="no-print mt-3 text-center text-xs text-gray-500">
          A4 portrait (210 × 297 mm) — print or save as PDF with background graphics enabled
        </p>
      </div>

      <div className="no-print mx-auto mt-8 max-w-xl rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-950">
        <strong>{t(language, 'importantBeforePrinting')}</strong>
        <p className="mt-2">{t(language, 'productionQrWarning')}</p>
        <p className="mt-3 font-medium">This label’s QR opens the tree page:</p>
        <code className="mt-1 block break-all rounded-lg bg-white px-3 py-2 text-xs text-primary-dark">{qr.url}</code>
        <p className="mt-2 text-xs text-amber-900/80">Tree ID: {qr.treeId}</p>
      </div>
    </div>
  );
}
